stages:
    - test
    - build
    - deploy

run test:
    stage: test
    image: node:20.10-bookworm-slim
    cache: # Cache modules using lock file. you can define it in root level for all jobs
        key:
            files:
                - package-lock.json
        paths:
            - node_modules/
    before_script:
        - apt update -y && apt install -y openssl
    script:
        - npm install
        - npm run test

build image:
    stage: build
    image: docker:24.0.7
    services:
        - docker:24.0.7-dind
    variables:
        IMAGE_NAME: itsyousef7677/nest-test
        IMAGE_TAG: "1.0"
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        - docker build -t $IMAGE_NAME:$IMAGE_TAG .
        - docker push $IMAGE_NAME:$IMAGE_TAG

.deploy:
    stage: deploy
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    when: manual
    before_script:
        - chmod 400 $SSH_KEY
    script:
        - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@111.111.111.111 "
          docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
          docker-compose -f .\docker-compose-prod.yml up -d"
