version: '3.7'

services:
  main:
    container_name: main
    # put image name instead of "build" for deployment on remote server
    image: itsyousef7677/nest-test
    # build:
    #   context: .
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/test?schema=public
      JWT_SECRET: caskl52@seca%
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123456789
    depends_on:
      postgres:
        condition: service_started
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      PG_DATA: /var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: